name: skin
services:
  skin:
    image: uhub.service.ucloud.cn/jsumc/blessing-skin
    restart: unless-stopped
    volumes:
      - ./data:/var/www/html/data
      - ./data/plugins:/var/www/html/plugins
      # sqlite 将数据库文件挂载到容器内，这里直接放data里一起挂载了
      # .env 中填容器内绝对路径！
      # - ./data/skin.db:/var/www/html/data/skin.db
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test:
        - CMD-SHELL
        - test -d data/public && test -f data/.env
      interval: 2s
      retries: 3
    depends_on:
      # mysql/mariadb/pgsql 需要等待数据库启动完成
      # - db
      - redis

  # PostgreSQL 数据库服务
  # db:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: username
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: blessingskin
  #   volumes:
  #     - ./db:/var/lib/postgresql/data
  #     - /etc/localtime:/etc/localtime:ro

  # MariaDB 数据库服务
  # db:
  #   image: mariadb:10.6
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: blessingskin
  #     MYSQL_USER: username
  #     MYSQL_PASSWORD: secret
  #   volumes:
  #     - ./db:/var/lib/mysql 
  #     - /etc/localtime:/etc/localtime:ro

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro

  http:
    image: uhub.service.ucloud.cn/jsumc/skin-http
    restart: unless-stopped
    ports:
      # 映射主机端口 8081 到容器端口 80
      - "8081:80"
    volumes:
      - type: bind
        source: ./data/public
        target: /var/www/html/public
        read_only: true
        bind:
          create_host_path: false
    depends_on:
      skin:
        condition: service_healthy
    # 手动启动 HTTP 容器，部署完成后注释掉
    profiles: ["http"]

  janus:
    # 使用对应数据库的 Janus 镜像
    image: uhub.service.ucloud.cn/jsumc/janus:sqlite
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ./data/.env
        target: /app/.env
        bind:
          create_host_path: false
      - type: bind
        source: ./data/storage/oauth-private.key
        target: /app/oauth-private.key
        read_only: true
        bind:
          create_host_path: false
      # sqlite 将数据库文件挂载到容器内（与 Blessing Skin 容器内路径相同）
      # - type: bind
      #   source: ./data/skin.db
      #   target: /var/www/html/data/skin.db
      #   bind:
      #     create_host_path: false
    # 手动启动 Janus 容器
    profiles: ["janus"]
    depends_on:
      # mysql/mariadb/pgsql 需要等待数据库启动完成
      # db:
      #   condition: service_started
      skin:
        condition: service_healthy
    networks:
      default:
        ipv4_address: 172.30.0.10

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.0.0/24
