server.modules = (
    "mod_extforward",
    "mod_fastcgi",
    "mod_proxy",
    "mod_rewrite"
)

server.document-root = "/var/www/html/public"
server.port = 80
extforward.headers = ("X-Forwarded-For")
extforward.forwarder = ( "172.30.0.0/24" => "trust" )
index-file.names = ( "index.php", "index.html", "index.htm" )

$HTTP["url"] =~ "^/api/janus($|/)" {
    proxy.server = ("" => ((
        "host" => "172.30.0.10",
        "port" => 3000
    )))
}

fastcgi.server = (".php" => ((
    "host" => "skin",
    "port" => 9000,
    "check-local" => "enable",
    "broken-scriptfilename" => "enable",
    "fix-root-scriptname" => "enable",
    "strip-request-uri" => "disable"
)))

url.rewrite-if-not-file = (
    "^/(.*)$" => "/index.php${qsa}"
)
